// <auto-generated />
using System;
using Linked.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Linked.Migrations.Linked
{
    [DbContext(typeof(LinkedContext))]
    [Migration("20190609223856_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Linked.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ClientID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Linked.Models.Employ", b =>
                {
                    b.Property<int>("TechnicianID");

                    b.Property<int>("ProjectID");

                    b.HasKey("TechnicianID", "ProjectID");

                    b.HasAlternateKey("ProjectID", "TechnicianID");

                    b.ToTable("Employ");
                });

            modelBuilder.Entity("Linked.Models.FeedBack", b =>
                {
                    b.Property<int>("TechnicianID");

                    b.Property<int>("ScoreSheetID");

                    b.HasKey("TechnicianID", "ScoreSheetID");

                    b.HasIndex("ScoreSheetID")
                        .IsUnique();

                    b.ToTable("FeedBack");
                });

            modelBuilder.Entity("Linked.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClientID");

                    b.Property<bool>("CompletionStatus");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("Level");

                    b.Property<int>("Role");

                    b.Property<string>("Title");

                    b.HasKey("ProjectID");

                    b.HasIndex("ClientID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Linked.Models.ScoreSheet", b =>
                {
                    b.Property<int>("ScoreSheetID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Compromiso");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Formalidad");

                    b.Property<int>("Profesionalismo");

                    b.Property<int>("Puntualidad");

                    b.Property<int>("Respeto");

                    b.HasKey("ScoreSheetID");

                    b.ToTable("ScoreSheet");
                });

            modelBuilder.Entity("Linked.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<int>("Role");

                    b.HasKey("TechnicianID");

                    b.ToTable("Technician");
                });

            modelBuilder.Entity("Linked.Models.Employ", b =>
                {
                    b.HasOne("Linked.Models.Project", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Linked.Models.Technician", "Technician")
                        .WithMany("Employers")
                        .HasForeignKey("TechnicianID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Linked.Models.FeedBack", b =>
                {
                    b.HasOne("Linked.Models.ScoreSheet", "ScoreSheet")
                        .WithOne("FeedBack")
                        .HasForeignKey("Linked.Models.FeedBack", "ScoreSheetID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Linked.Models.Technician", "Technician")
                        .WithMany("FeedBacks")
                        .HasForeignKey("TechnicianID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Linked.Models.Project", b =>
                {
                    b.HasOne("Linked.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
