// <auto-generated />
using System;
using Linked.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Linked.Migrations
{
    [DbContext(typeof(LinkedContext))]
    [Migration("20190608011814_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Linked.Models.FeedBack", b =>
                {
                    b.Property<int>("ProjectID");

                    b.Property<int>("UserID");

                    b.Property<int>("ScoreSheetID");

                    b.HasKey("ProjectID", "UserID", "ScoreSheetID");

                    b.HasIndex("ScoreSheetID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("FeedBack");
                });

            modelBuilder.Entity("Linked.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.HasKey("ProjectID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Linked.Models.ScoreSheet", b =>
                {
                    b.Property<int>("ScoreSheetID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Compromiso");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Formalidad");

                    b.Property<int>("Profesionalismo");

                    b.Property<int>("Puntualidad");

                    b.Property<int>("Respeto");

                    b.HasKey("ScoreSheetID");

                    b.ToTable("ScoreSheet");
                });

            modelBuilder.Entity("Linked.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("FirstName");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Linked.Models.FeedBack", b =>
                {
                    b.HasOne("Linked.Models.Project", "Project")
                        .WithMany("FeedBacks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Linked.Models.ScoreSheet", "ScoreSheet")
                        .WithOne("FeedBack")
                        .HasForeignKey("Linked.Models.FeedBack", "ScoreSheetID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Linked.Models.User", "User")
                        .WithMany("FeedBacks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
