// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesLinked.Models;

namespace RazorPagesLinked.Migrations
{
    [DbContext(typeof(RazorPagesLinkedContext))]
    partial class RazorPagesLinkedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("RazorPagesLinked.Models.FeedBack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TotalScore");

                    b.HasKey("ID");

                    b.ToTable("FeedBack_1");
                });

            modelBuilder.Entity("RazorPagesLinked.Models.FeedBackItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FeedBackID");

                    b.Property<string>("Question");

                    b.Property<int>("Score");

                    b.HasKey("ID");

                    b.HasIndex("FeedBackID");

                    b.ToTable("FeedBackItem");
                });

            modelBuilder.Entity("RazorPagesLinked.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Level");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("RazorPagesLinked.Models.FeedBackItem", b =>
                {
                    b.HasOne("RazorPagesLinked.Models.FeedBack")
                        .WithMany("Items")
                        .HasForeignKey("FeedBackID");
                });
#pragma warning restore 612, 618
        }
    }
}
